### ISSUE TITLE
2/8 멋쟁이 사자처럼 직장인 1기 A클래스 과제(Assginment)

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#1]
마감 : 2월 11일 화요일 강의 전

과제 내용 : 여러분이 꾸미고 싶은 형태의 CV를 제작한 후, 다음과 같은 형태로 과제 제출 글을 이 곳에 업로드해주세요

1. 과제 제출자 성명
2. 과제 제작 이미지 (스크린샷)
3. 과제 제작 과정에서 느낀 어려운 점 & 느낀 점
4. 깃허브 푸시 링크
5. 강사의 힌트

**Comment by aimclee** [comment]
예시과제)
`<!DOCTYPE html>
<html>
<head>
    <title>CV</title>
</head>
<body>
    <h1>aimclee(Andy)</h1>
    <img src="profile.jpg" alt=""> 
    <br>
    <h3>
        <a href="mailto:dhy04057@likelion.net">E-mail : dhy04057@likelion.net</a>
    </h3>
    <p>About me: Hello! I'm aimclee(Andy), Likelion_vn web development class instructor!<br>
    Although this course may be a little bit hard to you, I hope you guys enjoy it!<br>
    As you know, Learning something is tricky for the first time.<br>
    I was also non-IT background person.<br>
    If you have any questions about lecture, feel free to ask our instructors!<br>
    They are always open!<br> 
    Good luck :)</p>

    <h3>Careers</h3>
    <ul>
        <li>LIKELION member</li>
        <li>LIKELION member</li>
        <li>LIKELION member</li>
    </ul>

    <h3>Social Network Service account</h3>
    <ol>
        <li>
           <a href="http://instagram.com"> instagram</a>
        </li>
        <li>
            <a href="http://facebook.com">facebook</a>
        </li>
    </ol>

    <form action="" method="">
        <label for = "comment">Comment</label>
        <input id = "comment" type="text" value = "question">
        <input type="submit">
    </form>
</body>
</html>`

기타 자료 : 프로필 이미지
![profile](https://user-images.githubusercontent.com/46996475/73256614-cddf2380-41f4-11ea-89e2-e6a7e23d4967.jpg)

**Comment by RyanKor** [comment]
제출자 : 김승태

이미지 1 : home.html
![image](https://user-images.githubusercontent.com/40455392/73587607-beabee80-44f0-11ea-8270-257cd8fa2577.png)

이미지 2 : result.html
![image](https://user-images.githubusercontent.com/40455392/73587621-df744400-44f0-11ea-8ac3-162b3539ee78.png)\

과제 제작하면서 어려웠던 점 & 느낀 점: 강의가 너무 빨랐어요 ㅠㅠ

깃허브 url : https://github.com/RyanKor/test-
