### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 B클래스 5-1주차 과제 (~3/12 목요일까지 제출)

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#10]
Word Count 복습하기

1. 워드 카운트 **3번 이상** 똑같이 따라 치면서 MVT Pattern을 이해합니다.

2. (Optional) **Django에 CSS를 적용**해볼까요?

결과물

![image](https://user-images.githubusercontent.com/40455392/76135524-1c84a680-605a-11ea-8356-7918c2eaafde.png)

![image](https://user-images.githubusercontent.com/40455392/76135527-227a8780-605a-11ea-804e-a22ecb97c54f.png)

- [x] 양원석
- [ ] 서강원
- [ ] 고동기
- [ ] 김한비
- [x] 이병훈
- [ ] 이장훈
- [x] 이가연
- [ ] 송혜령
- [ ] 김준영
- [ ] 김영진
- [ ] 조민성
- [ ] 권오일

**Comment by Kayaleeeee** [comment]
1. 이가연
2. Django 결과물 
![image](https://user-images.githubusercontent.com/60032720/76402437-cbacdf00-63c6-11ea-8036-f881f42ea781.png)

**Comment by bhlee6689** [comment]
1. 이병훈
2. Django 결과물
![image](https://user-images.githubusercontent.com/61373206/76499496-695ce880-6471-11ea-838f-441177e1b6b1.png)
![image](https://user-images.githubusercontent.com/61373206/76499507-6bbf4280-6471-11ea-970f-f9d243f1f8ed.png)

**Comment by EthanYang25** [comment]
1. 양원석
2. Django 결과물
* 지난주에 크롤링 과제를 제출하지 못해서, 크롤링 과제 연장선 상에서 하였습니다.  환율정보 가지고 온 뒤, 계산하여 평소대비 이익인지 손해인지 알려주는 내용입니다.
![image](https://user-images.githubusercontent.com/61373197/76519806-409a1a80-6494-11ea-99bf-61915080e6e5.png)
![image](https://user-images.githubusercontent.com/61373197/76520008-9d95d080-6494-11ea-8f8c-fc39d2678d2c.png)
