### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 A클래스 5-2 주차 과제 (~3/14 토요일까지 제출)

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#11]
1. CRUD의 CR 부분을 3번 반복해서 코드를 작성하는 연습을 진행합니다.

2. (Optional) CSS를 활용해 게시판 형태로 꾸며봅니다.

결과물

![image](https://user-images.githubusercontent.com/40455392/76305987-b6697f00-62f8-11ea-9913-9b3134ac3751.png)

- [x] 김진성
- [ ] 이민선
- [ ] 윤보나
- [ ] 권신우
- [ ] 김은혁
- [ ] 송현승
- [x] 권현우
- [ ] 양은정
- [ ] 유영준
- [ ] 최송
- [ ] 이창목
- [ ] 김익용

**Comment by everyvn** [comment]
1. 김진성
2. 
![스크린샷 2020-03-12 23 29 02](https://user-images.githubusercontent.com/12597450/76544421-98e41300-64ba-11ea-8ecf-5890ae3133f9.png)
3. https://github.com/everyvn/djangoCR

**Comment by hw-kwon** [comment]
![image](https://user-images.githubusercontent.com/61343808/76676110-bcaa7480-65f2-11ea-8d00-ebf5e0fa9cdd.png)
![image](https://user-images.githubusercontent.com/61343808/76676115-c9c76380-65f2-11ea-8f56-4d4e7dfea0b6.png)
![image](https://user-images.githubusercontent.com/61343808/76676117-d2b83500-65f2-11ea-9056-56c873f162ff.png)

**Comment by Daniel-song2719** [comment]
송현승
![1번](https://user-images.githubusercontent.com/61343838/76676311-c46b1880-65f4-11ea-9d74-b92559a92d71.png)
![2번](https://user-images.githubusercontent.com/61343838/76676313-cb922680-65f4-11ea-87f7-1adfc1916794.png)
![3번](https://user-images.githubusercontent.com/61343838/76676320-d3ea6180-65f4-11ea-8c1a-550b6955d232.png)
![4번](https://user-images.githubusercontent.com/61343838/76676323-dbaa0600-65f4-11ea-8886-3daec7894d29.png)
