### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 B클래스 5-2 주차 과제 (~3/15 일요일까지 제출)

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#12]
1. CRUD의 CR 부분을 3번 반복해서 코드를 작성하는 연습을 진행합니다.

2. (Optional) CSS를 활용해 게시판 형태로 꾸며봅니다.

결과물

![image](https://user-images.githubusercontent.com/40455392/76305987-b6697f00-62f8-11ea-9913-9b3134ac3751.png)

- [ ] 양원석
- [x] 서강원
- [ ] 고동기
- [ ] 김한비
- [ ] 이병훈
- [ ] 이장훈
- [x] 이가연
- [x] 송혜령
- [ ] 김준영
- [ ] 김영진
- [ ] 조민성
- [ ] 권오일

**Comment by Kayaleeeee** [comment]
1. 이가연
2. 과제 결과물
![image](https://user-images.githubusercontent.com/60032720/76636165-ef6d5200-658b-11ea-96a3-c3e859b4de58.png)

**Comment by suhkangwon** [comment]
서강원
<img width="765" alt="assign5-2_2" src="https://user-images.githubusercontent.com/61373175/76686583-12146f00-664f-11ea-9f46-ae2aaebadab8.PNG">

**Comment by hyer02** [comment]
1. 송혜령 
![스크린샷 2020-03-15 16 52 51](https://user-images.githubusercontent.com/61373180/76699227-0e7bf900-66de-11ea-9d3a-dfd6e660fe24.png)
![스크린샷 2020-03-15 16 53 03](https://user-images.githubusercontent.com/61373180/76699229-15a30700-66de-11ea-9c31-2b07a7c6ca4f.png)
![스크린샷 2020-03-15 16 57 09](https://user-images.githubusercontent.com/61373180/76699230-16d43400-66de-11ea-95d3-98417e7410d8.png)

**Comment by bhlee6689** [comment]
1. 이병훈
2, 과제결과물
![image](https://user-images.githubusercontent.com/61373206/76704664-27e86980-670d-11ea-9976-0fed98bdce70.png)
![image](https://user-images.githubusercontent.com/61373206/76704677-3f275700-670d-11ea-9dbd-61f3b609af46.png)
![image](https://user-images.githubusercontent.com/61373206/76704691-55351780-670d-11ea-9c52-6fc9342fdfe6.png)

**Comment by bhlee6689** [comment]
1. 이병훈
2. 과제 결과물
![image](https://user-images.githubusercontent.com/61373206/76704909-d17c2a80-670e-11ea-9f53-64c69c3f2afe.png)
![image](https://user-images.githubusercontent.com/61373206/76704922-dc36bf80-670e-11ea-826d-350e3fc52223.png)
![image](https://user-images.githubusercontent.com/61373206/76704930-e6f15480-670e-11ea-9865-6a166555d301.png)

**Comment by bhlee6689** [comment]
> 1. 이병훈
> 2. 과제 결과물
>    ![image](https://user-images.githubusercontent.com/61373206/76704909-d17c2a80-670e-11ea-9f53-64c69c3f2afe.png)
>    ![image](https://user-images.githubusercontent.com/61373206/76704922-dc36bf80-670e-11ea-826d-350e3fc52223.png)
>    ![image](https://user-images.githubusercontent.com/61373206/76704930-e6f15480-670e-11ea-9865-6a166555d301.png)

강사님들 일자내에 숙제 제출할수있도록 도와주셔서 감사해요
