### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 B클래스 6-1 주차 과제 (~3/19 목요일까지 제출)

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#14]
1. CRUD  전체를 다시 한 번 타이핑 해볼까요!?

2. 페이지 캡처 이미지
![image](https://user-images.githubusercontent.com/40455392/76855468-c72f6d00-6883-11ea-855a-bad6d0b4c4c2.png)

3. 깃헙 URL

과제 업로드 창을 늦게 올려서 죄송합니다!!!
- [ ] 양원석
- [ ] 서강원
- [ ] 고동기
- [ ] 김한비
- [ ] 이병훈
- [ ] 이장훈
- [ ] 이가연
- [x] 송혜령
- [ ] 김준영
- [ ] 김영진
- [ ] 조민성
- [ ] 권오일

**Comment by hyer02** [comment]
1. 송혜령
2. 캡처 이미지 
![스크린샷 2020-03-19 20 02 55](https://user-images.githubusercontent.com/61373180/77070429-caaa2c00-6a1c-11ea-9407-a795aa0e0839.png)
![스크린샷 2020-03-19 20 03 37](https://user-images.githubusercontent.com/61373180/77070433-cbdb5900-6a1c-11ea-82f1-3d3ae3b7e6bc.png)

3.
