### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 B클래스 6-2 주차 과제 (~3/22 일요일까지 제출)

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#16]
1. 썸네일, 이미지를 넣어서 CRUD를 만들어 보아요 (3회 반복하기)

2. CRUD 제작한 내용을 스크린샷으로 캡쳐해서 올려 주세요.
![image](https://user-images.githubusercontent.com/40455392/77138203-a9d8e980-6aa3-11ea-9908-f1e160ca0611.png)

3.깃헙 주소를 함께 첨부해 올려주세요

- [ ] 양원석
- [ ] 서강원
- [ ] 고동기
- [ ] 김한비
- [ ] 이병훈
- [ ] 이장훈
- [x] 이가연
- [ ] 송혜령
- [ ] 김준영
- [ ] 김영진
- [ ] 조민성
- [ ] 권오일

**Comment by Kayaleeeee** [comment]
1. 이가연
2.캡쳐본 이미지


![스크린샷 2020-03-21 오후 2 25 04](https://user-images.githubusercontent.com/60032720/77220226-43c29400-6b81-11ea-9907-59c14bd6284c.png)
