### ISSUE TITLE
2/29 멋쟁이 사자처럼 직장인 1기 A 클래스 과제

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#3]
### 과제 내용
![image](https://user-images.githubusercontent.com/40455392/75599710-00bd5580-5ada-11ea-9230-5c16719fa9eb.png)

![image](https://user-images.githubusercontent.com/40455392/75599714-09ae2700-5ada-11ea-865d-ca9a08ad6fd3.png)

![image](https://user-images.githubusercontent.com/40455392/75599725-17fc4300-5ada-11ea-8609-29333457860c.png)

### 제출 방법

```
1. 해당 게시글 아래에 댓글 형태로 과제를 제출합니다.

2. 본인의 이름을 먼저 명시해주세요

3. 과제를 업로드한 레포지토리 링크를 붙여넣어 주세요

4. 과제 이미지를 캡쳐해서 복사 & 붙여넣기를 해주세요.
```

수강생 명단
- [ ] 김진성
- [ ] 이민선
- [ ] 윤보나
- [ ] 권신우
- [ ] 김은혁
- [x] 송현승
- [ ] 권현우
- [ ] 양은정
- [ ] 유영준
- [ ] 최송
- [ ] 이창목
- [ ] 김익용

**Comment by aimclee** [comment]
과제 제출 예시입니다!

1. 이름 : 이민철
2. github url (github.com/깃허브 계정 이름/assignment-hochiminh-1st)
3. 과제 이미지 캡쳐 후 복사 & 붙여넣기

**Comment by Daniel-song2719** [comment]
지난 과제 제출 입니다!

송현승

https://github.com/Daniel-song2719/Assignment

![calculator](https://user-images.githubusercontent.com/61343838/75622090-3abc5380-5bcf-11ea-9fe8-fa4ab569a5c5.png)
![character](https://user-images.githubusercontent.com/61343838/75622092-3db74400-5bcf-11ea-8ccd-4838ea07062d.png)
![list, tuple](https://user-images.githubusercontent.com/61343838/75622093-3ee87100-5bcf-11ea-9868-465d4cdeaad1.png)

**Comment by RyanKor** [comment]
> 지난 과제 제출 입니다!
> 
> 송현승
> 
> https://github.com/Daniel-song2719/Homeworks
> 
> ![calculator](https://user-images.githubusercontent.com/61343838/75622090-3abc5380-5bcf-11ea-9fe8-fa4ab569a5c5.png)
> ![character](https://user-images.githubusercontent.com/61343838/75622092-3db74400-5bcf-11ea-8ccd-4838ea07062d.png)
> ![list, tuple](https://user-images.githubusercontent.com/61343838/75622093-3ee87100-5bcf-11ea-9868-465d4cdeaad1.png)

훌륭합니다! 과제 양식에 맞게 잘 작성해주셨군요!
