### ISSUE TITLE
멋쟁이 사자처럼 호치민 1기 A클래스 4-1주차 과제 (~3/3 화요일까지 제출)

### ISSUE THREAD

**Issue by aimclee** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#5]
![image](https://user-images.githubusercontent.com/46996475/75623997-a2c86500-5be2-11ea-96cb-f3f0e34af44c.png)

![image](https://user-images.githubusercontent.com/46996475/75624000-b1168100-5be2-11ea-97a8-d9af96248b06.png)

![image](https://user-images.githubusercontent.com/46996475/75624002-ba9fe900-5be2-11ea-9f6e-0aba6aaefac8.png)

* 과제 형식 
1. 이름 : 이민철
2. 과제 레포지토리 깃허브 url
3. 터미널 캡쳐사진

- [x] 김진성
- [ ] 이민선
- [ ] 윤보나
- [ ] 권신우
- [ ] 김은혁
- [ ] 송현승
- [ ] 권현우
- [ ] 양은정
- [ ] 유영준
- [ ] 최송
- [ ] 이창목
- [ ] 김익용

**Comment by everyvn** [comment]
1. 김진성
2. https://github.com/everyvn/homeWork-API-
3. 터미널 캡처
<img width="1314" alt="스크린샷 2020-03-01 20 15 03" src="https://user-images.githubusercontent.com/12597450/75626339-6eac6e80-5bf9-11ea-979d-d9d53bdfbc35.png">
