### ISSUE TITLE
멋쟁이 사자처럼 호치민 1기 B클래스 4-1주차 과제 (~3/5 목요일까지 제출)

### ISSUE THREAD

**Issue by aimclee** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#6]
![image](https://user-images.githubusercontent.com/46996475/75624038-02267500-5be3-11ea-8253-464a9aa01827.png)

![image](https://user-images.githubusercontent.com/46996475/75624040-09e61980-5be3-11ea-880d-bc6e9ab9b2be.png)

![image](https://user-images.githubusercontent.com/46996475/75624036-f935a380-5be2-11ea-987e-77f31d589e43.png)

* 과제 형식

1. 이름 : 이민철
2. 과제 제출 github_url
3. 터미널 캡쳐 화면

- [x] 양원석
- [x] 서강원
- [x] 고동기
- [ ] 김한비
- [x] 이병훈
- [ ] 이장훈
- [x] 이가연
- [ ] 송혜령
- [ ] 김준영
- [ ] 김영진
- [ ] 조민성
- [ ] 권오일

**Comment by kohdongki** [comment]
1. 고동기
2. https://github.com/kohdongki/assignment-hochiminh-1st/blob/master/0301_assignment1.py
3. 터미널 캡쳐 화면
<img width="605" alt="스크린샷 2020-03-01 오후 6 03 11" src="https://user-images.githubusercontent.com/61373198/75624472-f76ddf00-5be6-11ea-8898-44850c893413.png">

**Comment by bhlee6689** [comment]
1. 이병훈
2. https://github.com/bhlee6689/assignment-hochiminh-1st/blob/master/ex4-1.py
3. 터미널 캡쳐 화면
![image](https://user-images.githubusercontent.com/61373206/75638320-db595480-5c5d-11ea-91b8-b4850ffbdae9.png)

**Comment by Kayaleeeee** [comment]
1. 이가연
2. https://github.com/Kayaleeeee/assignment-hochiminh-1st/blob/master/instagram.py
2-1. https://github.com/Kayaleeeee/assignment-hochiminh-1st/blob/master/google_maps.py
3. 터미널 캡쳐 화면

![무제](https://user-images.githubusercontent.com/60032720/75768220-481c3e00-5d87-11ea-8456-94b2c01e7f04.jpeg)

![무제](https://user-images.githubusercontent.com/60032720/75866219-0bfce200-5e48-11ea-8154-35aa4bdb41b8.jpeg)

**Comment by EthanYang25** [comment]
1. 양원석
2-1. https://github.com/EthanYang25/homework/blob/master/google_assignmnet.py
2-2. https://github.com/EthanYang25/homework/blob/master/insta_assignment.py
3. 캡쳐화면


![image](https://user-images.githubusercontent.com/61373197/75956966-a06c5080-5eeb-11ea-8501-832df591555d.png)


![image](https://user-images.githubusercontent.com/61373197/75957069-cf82c200-5eeb-11ea-9bb5-35627bc016dd.png)

**Comment by suhkangwon** [comment]
1.서강원


2-1과제(인스타 API)
https://github.com/suhkangwon/assignment-hochiminh-1st/blob/master/assignment_instaram_API.py

2-2과제(구글 API)
https://github.com/suhkangwon/assignment-hochiminh-1st/blob/master/assignment_google_API.py
