### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 A클래스 4-2주차 과제 (~3/7 토요일까지 제출)

### ISSUE THREAD

**Issue by aimclee** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#7]
![image](https://user-images.githubusercontent.com/46996475/75959305-8e40e100-5ef0-11ea-9f08-07a4f061e275.png)

- 과제제출형식

1. 성함
2. 과제 깃허브 링크
3. 터미널/결과 캡쳐화면

- [x] 김진성
- [ ] 이민선
- [ ] 윤보나
- [ ] 권신우
- [x] 김은혁
- [x] 송현승
- [ ] 권현우
- [ ] 양은정
- [ ] 유영준
- [x] 최송
- [ ] 이창목
- [ ] 김익용

**Comment by everyvn** [comment]
1. 김진성
2. https://github.com/everyvn/crawling/blob/master/homework.py
3. 
![스크린샷 2020-03-05 22 41 26](https://user-images.githubusercontent.com/12597450/75997795-7427f280-5f32-11ea-8139-08a3008442c8.png)

**Comment by keh9104** [comment]
1. 김은혁
2. https://github.com/keh9104/assignment-hochiminh-first/blob/master/week4-2/fortune.py
3. 
![fortune](https://user-images.githubusercontent.com/61343846/76121784-0e696280-6027-11ea-98d2-ad5521d35847.PNG)

**Comment by Daniel-song2719** [comment]
1. 송현승
2. https://github.com/Daniel-song2719/Assignment
3. 
![02](https://user-images.githubusercontent.com/61343838/76137761-0fc07c80-6073-11ea-9fe0-d9eaa55190e5.png)
