### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 B클래스 4-2주차 과제 (~3/8 일요일까지 제출)

### ISSUE THREAD

**Issue by aimclee** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#8]
![image](https://user-images.githubusercontent.com/46996475/75959305-8e40e100-5ef0-11ea-9f08-07a4f061e275.png)

- 과제제출형식

1. 성함
2. 과제 깃허브 링크
3. 터미널/결과 캡쳐화면

- [ ] 양원석
- [ ] 서강원
- [ ] 고동기
- [ ] 김한비
- [ ] 이병훈
- [ ] 이장훈
- [x] 이가연
- [ ] 송혜령
- [ ] 김준영
- [ ] 김영진
- [ ] 조민성
- [ ] 권오일

**Comment by Kayaleeeee** [comment]
1. 이가연
2. https://github.com/Kayaleeeee/assignment-hochiminh-1st/blob/master/crawling.py
3. 
![image](https://user-images.githubusercontent.com/60032720/76144839-68ba0000-60c7-11ea-971c-acea8dea2384.png)
