### ISSUE TITLE
멋쟁이사자처럼 호치민 1기 A클래스 5-1 주차 과제 (~3/10 월요일까지 제출)

### ISSUE THREAD

**Issue by RyanKor** [LIKELION-VN-WORKS/LIKE-LION-VN-WORKS-1st#9]
Word Count 복습하기

1. 워드 카운트 **3번 이상** 똑같이 따라 치면서 MVT Pattern을 이해합니다.

2. (Optional) **Django에 CSS를 적용**해볼까요?

결과물

![image](https://user-images.githubusercontent.com/40455392/76135524-1c84a680-605a-11ea-8356-7918c2eaafde.png)

![image](https://user-images.githubusercontent.com/40455392/76135527-227a8780-605a-11ea-804e-a22ecb97c54f.png)

- [x] 김진성
- [ ] 이민선
- [ ] 윤보나
- [ ] 권신우
- [x] 김은혁
- [x] 송현승
- [x] 권현우
- [ ] 양은정
- [x] 유영준
- [ ] 최송
- [ ] 이창목
- [ ] 김익용

**Comment by everyvn** [comment]
1. 김진성
2. 이미지 캡쳐
![스크린샷 2020-03-09 22 11 14](https://user-images.githubusercontent.com/12597450/76228657-96cc4b00-6253-11ea-950f-db58a93669e3.png)
3. 깃허브 주소 : https://github.com/everyvn/homework-wordcount

**Comment by Daniel-song2719** [comment]
송현승
https://github.com/Daniel-song2719/Assignment
![0101](https://user-images.githubusercontent.com/61343838/76300192-e90e7a00-62ee-11ea-92b7-af646629fdd7.png)
![0202](https://user-images.githubusercontent.com/61343838/76300200-eb70d400-62ee-11ea-99e4-62a09c1a829a.png)
![0303](https://user-images.githubusercontent.com/61343838/76300202-ec096a80-62ee-11ea-82e3-69df86a26b0f.png)

**Comment by June8192** [comment]
1. 유영준
2. 이미지 캡쳐 
 
![영준1](https://user-images.githubusercontent.com/61343799/76297774-fde90e80-62ea-11ea-9326-774246e74f4c.PNG)
![영준2](https://user-images.githubusercontent.com/61343799/76297783-ffb2d200-62ea-11ea-92a0-52ba64a5ad3c.PNG)

3. 깃허브 주소:https://github.com/June8192/Homework_wordcount

**Comment by hw-kwon** [comment]
![image](https://user-images.githubusercontent.com/61343808/76302155-13ae0200-62f2-11ea-8ddf-5f18831de79a.png)
![image](https://user-images.githubusercontent.com/61343808/76302142-0d1f8a80-62f2-11ea-8949-3400b770e352.png)
깃허브주소 https://github.com/hw-kwon/Homeworks

**Comment by keh9104** [comment]
1. 김은혁
2. 
![home](https://user-images.githubusercontent.com/61343846/76305509-d9dffa00-62f7-11ea-8d3a-49f49afe01cc.PNG)
![result](https://user-images.githubusercontent.com/61343846/76305514-dba9bd80-62f7-11ea-97b6-0d59f50dd640.PNG)
3. https://github.com/keh9104/assignment-hochiminh-first/tree/master/mlc/wc_p
